name: .NET Build

on:
  push: # Configura o workflow para ser acionado sempre que houver um push para qualquer branch do repositório.
    branches:
      - '**' # Monitora todos os branches
  schedule:
    - cron: '0 * * * *' # Executa no início de cada hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0' # Substitua pela versão do .NET necessária

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore --configuration Release